### ISSUE TITLE
Add script on build to add copyright

### ISSUE THREAD

**Issue by aramshiva** [jaspermayone/website#1]
add a script to add a copyright to all images that don't have one. this should run on build in the  `next.config.js` file.

**Comment by aramshiva** [comment]
cc @jaspermayone

**Comment by jaspermayone** [comment]
oh perf.

**Comment by jaspermayone** [comment]
tysm @aramshiva!

**Comment by jaspermayone** [comment]
see https://www.aram.sh/photos for reference

**Comment by jaspermayone** [comment]
closing bc I am going to do something different for v2, not sure quite what yet
