### ISSUE TITLE
V2 photos page

### ISSUE THREAD

**Issue by jaspermayone** [jaspermayone/website#43]

**Comment by aramshiva** [comment]
If you used Flickr to store your images you can just use a function like [this](https://github.com/aramshiva/website/blob/v10.1/pages/api/photos.ts) to fetch the images really easily and doesn't require you to upload the images hardcoded

**Comment by jaspermayone** [comment]
Oh yea that'd be cool

**Comment by jaspermayone** [comment]
I'll do that :)

**Comment by jaspermayone** [comment]
Can you pull metadata with the flickr api? it'd be cool to get details like what device it was shot on.

**Comment by jaspermayone** [comment]
Flickr only allows 1000 images :(

**Comment by jaspermayone** [comment]
Ugh my photos don't have the metadata 😠

**Comment by jaspermayone** [comment]
Just going to go with out it, it'd be cool if I had it but it isn't that important
