### ISSUE TITLE
[BUG] Photo Metadata is broken after move to S3

### ISSUE THREAD

**Issue by jaspermayone** [jaspermayone/website#49]

**Comment by VividhPandey003** [comment]
Hey @jaspermayone can you tell me more about this issue, I would like to work on it

**Comment by jaspermayone** [comment]
Hi @VividhPandey003,

In commit https://github.com/jaspermayone/website/commit/8c53a88debedaf86622cc8de4f9b5927ba23a988

I moved to S3 for image storing as part of #50.

Now, all the metadata for the images shows as undefined, even though I know there's metadata on the image.

**Comment by jaspermayone** [comment]
Does that make sense?

**Comment by ofluffydev** [comment]
Why using S3?

**Comment by ofluffydev** [comment]
And just to confirm this is causing #50 ?

**Comment by jaspermayone** [comment]
No, I think 50 is related though.

**Comment by jaspermayone** [comment]
S3 because the files are too large to host on vercel as part of the site, and s3 is the standard for these types of things

**Comment by jaspermayone** [comment]
Ahhhh so this is tied with #50

**Comment by jaspermayone** [comment]
Bizzare

**Comment by jaspermayone** [comment]
I want to go back to local photos but Vercel is being a pain

**Comment by ofluffydev** [comment]
Also the metadata is showing in the console but not the website.

**Comment by aramshiva** [comment]
Doesn’t <Image> remove metadata? It’s optimizing the imageOn Sep 27, 2024, at 7:22 AM, Kaden Frisk ***@***.***> wrote:﻿
Also the metadata is showing in the console but not the website.

**Comment by jaspermayone** [comment]
I don't think so? I am displaying the metadata as an overlay so the <Image> tag shouldn’t matter
