### ISSUE TITLE
[BUG] /photos page takes a suuuuuper long time to load

### ISSUE THREAD

**Issue by jaspermayone** [jaspermayone/website#50]

**Comment by Lokendra-sinh** [comment]
@jaspermayone do you want me to take it up? The root cause of this slowness seems to be the additional metadeta api call we are making.

**Comment by jaspermayone** [comment]
Sure!

**Comment by Lokendra-sinh** [comment]
@jaspermayone on average the server is taking around 5-6 seconds to retrieve the meta data of a single image. The download and the request itself are really fast. 

Just to make sure we're considering everything...is there any pre-processing or an additional service in between the client and server?

**Comment by Lokendra-sinh** [comment]
@jaspermayone one of the images taking around 18s just to fetch the metadata of an image...it should happen in ms.
![Image](https://github.com/user-attachments/assets/9ab75b69-9192-40ac-801c-279d713801fe)

**Comment by jaspermayone** [comment]
That would be the ones @Lokendra-sinh!

**Comment by Lokendra-sinh** [comment]
@jaspermayone for reducing load time, we can have batch processing. I'm currently working on that and hopefully will raise a PR soon.
