### ISSUE TITLE
Vercel Build Failing due to serverless function too large

### ISSUE THREAD

**Issue by jaspermayone** [jaspermayone/website#51]
![CleanShot 2024-09-27 at 09 51 16@2x](https://github.com/user-attachments/assets/762aa075-5c0d-487b-9506-81c82c5edba6)

**Comment by Lokendra-sinh** [comment]
@jaspermayone and this is happening becuase we moved to local?

**Comment by jaspermayone** [comment]
I used to use local, then added more photos and was getting these errors so I moved to s3, but the loading time for s3 is too long so I want to move back to local and fix the error

**Comment by Lokendra-sinh** [comment]
@jaspermayone well there's a solution for that I believe. we could load photos in chunks / batches to reduce the overall size of the function. We might need to implement some form of chunking...a pagination or maybe infinite scrolling thing. 

Let me know what do you think? This approach would be more scalable and can handle any number of images without any issues.

**Comment by jaspermayone** [comment]
Ok, that might help, but I don't think it will solve the vercel error

**Comment by Lokendra-sinh** [comment]
@jaspermayone we can take a stab at it by using native fetch and a small size exif package if it exists. This might help us reduce the overall function size.

**Comment by Lokendra-sinh** [comment]
@jaspermayone we can take a stab at it by using native fetch and a small size exif package if it exists. This might help us reduce the overall function size.

**Comment by jaspermayone** [comment]
> @jaspermayone we can take a stab at it by using native fetch and a small size exif package if it exists. This might help us reduce the overall function size.

@Lokendra-sinh I don't think the package sizes are the issue here.

**Comment by jaspermayone** [comment]
> What's the logic for getting the metadata? Is it already attached and ready on s3?.. Also the images already load in chunks in most browsers I think

I am not sure if the metadata is on s3, but we're moving back to local anyways.

**Comment by ofluffydev** [comment]
CDN would be better idk if s3 even has servers spread out I thought it was mainly for large files.

**Comment by jaspermayone** [comment]
S3 is a type of cdn :)

**Comment by ofluffydev** [comment]
Does S3 have edge servers

**Comment by Lokendra-sinh** [comment]
@jaspermayone steps to reproduce this issue?

**Comment by jaspermayone** [comment]
> @jaspermayone steps to reproduce this issue?

@Lokendra-sinh it's when Vercel builds the site

**Comment by ofluffydev** [comment]
The files are too big we can't use local and bypass file sizes...

**Comment by jaspermayone** [comment]
I don't believe that's what's causing the errors

**Comment by jaspermayone** [comment]
oh no wait it is

**Comment by jaspermayone** [comment]
so we need to move back to s3 and then just fix the load times.

**Comment by Lokendra-sinh** [comment]
@jaspermayone Yes. Currently we are rendering all the images at once. Probably we can avoid this and have some batch rendering method in place. 

or do you have something else on your mind?

**Comment by jaspermayone** [comment]
That's fine.

**Comment by jaspermayone** [comment]
The metadata should be on the s3 image

**Comment by Lokendra-sinh** [comment]
@jaspermayone inconsistency with metadata...are we okay with this? 
Few properties are missing for some of the images

<img width="471" alt="image" src="https://github.com/user-attachments/assets/fd6a435d-5ab3-4733-8d42-232d16eb866f">

<img width="471" alt="image" src="https://github.com/user-attachments/assets/e4c43a28-6dd7-4b46-a33e-295e3fa34c17">

**Comment by jaspermayone** [comment]
Yes, that's fine

**Comment by Lokendra-sinh** [comment]
@jaspermayone do you want me to create a new issue for batch method we discussed....or are we good with the current setup?

Also I noticed we are not directly communicating with S3...resulting more latency. We have a load balancer before the request goes to S3?

Would really appreciate your clarification on this :)

**Comment by jaspermayone** [comment]
New issue would be great.

What do you mean we aren't directly communicating with S3?

**Comment by Lokendra-sinh** [comment]
@jaspermayone did a quick lookup and I believe we are not directly communicating with S3. 
Let me know if I'm missing something :)

nslookup s3.jaspermayone.com
➜  jaspermayone git:(main) ✗ nslookup s3.jaspermayone.com
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
Name:   s3.jaspermayone.com
Address: 65.19.76.238

**Comment by ofluffydev** [comment]
I don't think we should be "fine" with not having meta data consistently, if it's not actually present on the image then unknown is fine but I doubt images are just missing every single property.

**Comment by jaspermayone** [comment]
> @jaspermayone did a quick lookup and I believe we are not directly communicating with S3. Let me know if I'm missing something :)
> 
> nslookup s3.jaspermayone.com ➜ jaspermayone git:(main) ✗ nslookup s3.jaspermayone.com Server: 192.168.0.1 Address: 192.168.0.1#53
> 
> Non-authoritative answer: Name: s3.jaspermayone.com Address: 65.19.76.238

The non-authoritative can be ignored, that's inside the local network. It **is** communicating directly.

**Comment by ofluffydev** [comment]
Can we maybe not move between platforms over and over. Keep on s3 or whatever large file service, and we fix the actual issues which are in the website 😭

**Comment by jaspermayone** [comment]
> I don't think we should be "fine" with not having meta data consistently, if it's not actually present on the image then unknown is fine but I doubt images are just missing every single property.

some of the images have no metadata, as they were exported off instagram bc I can't find the original, so that's why there's no metadata

**Comment by jaspermayone** [comment]
> Can we maybe not move between platforms over and over. Keep on s3 or whatever large file service, and we fix the actual issues which are in the website 😭

I am fine with staying with S3.

**Comment by jaspermayone** [comment]
Temp fix pushed
